apps/feedback/urls.py
from django.conf.urls import patterns, include, url

from feedback.views import *

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'customerfeedback.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', LoginPageView.as_view(), name='login-page'),
    url(r'^admin/?$', AdminHomeView.as_view(), name='admin-home'),
    url(r'^logout/?$', LogoutView.as_view(), name='logout'),
    #companies
    url(r'^admin/companies/?$', AdminCompaniesView.as_view(), name='admin-companies'),
    url(r'^admin/companies/create/?$', CreateCompanyView.as_view(), name='create-company'),
    url(r'^admin/companies/(?P<company_id>\d+)/edit/?$', EditCompanyView.as_view(), name='edit-company'),
    url(r'^admin/companies/(?P<company_id>\d+)/delete/?$', DeleteCompanyView.as_view(), name='delete-company'),
    url(r'^admin/companies/(?P<company_id>\d+)/feedback/?$', CompanyFeedbackView.as_view(), name='feedback-company'),
    #admin employees
    url(r'^admin/employees/?$', AdminEmployeesView.as_view(), name='admin-employees'),
    url(r'^admin/employees/create/?$', CreateEmployeeView.as_view(), name='create-employee'),
    url(r'^admin/employees/(?P<employee_id>\d+)/edit/?$', EditEmployeeView.as_view(), name='edit-employee'),
    url(r'^admin/employees/(?P<employee_id>\d+)/delete/?$', DeleteEmployeeView.as_view(), name='delete-employee'),
    url(r'^admin/employees/(?P<employee_id>\d+)/assign-companies/?$', AssignCompanyView.as_view(), name='assign-companies'),
    #employee urls
    url(r'^employee/?$', EmployeeHomeView.as_view(), name='employee-home'),
    url(r'^employee/(?P<company_id>\d+)/feedback/?$', EmployeeFeedbackView.as_view(), name='feedback'),
)

customerfeedback/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'customerfeedback.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'', include('feedback.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/feedback/models.py
from django.db import models
from django.contrib.auth.models import User
from annoying.fields import AutoOneToOneField

# Create your models here.

class SystemUser(models.Model):
    ADMIN, EMPLOYEE = range(2)
    ROLE_CODES = (
        (ADMIN, 'Admin'),
        (EMPLOYEE, 'Employee')
    )
    user = AutoOneToOneField(User)
    role = models.IntegerField(choices=ROLE_CODES, default=EMPLOYEE)
    
    class Meta:
        permissions = (
            ('add_employee', 'Add Employee'),
            ('edit_employee', 'Edit Employee'),
            ('delete_employee', 'Delete Employee'),
            ('add_admin', 'Add admin'),
            ('edit_admin', 'Edit admin'),
            ('delete_admin', 'Delete admin'),
        )
    
    def __unicode__(self, ):
        return self.user.first_name
        
    @property
    def is_admin(self, ):
        #check if the user is an admin
        return self.role == SystemUser.ADMIN
        
    @property
    def is_employee(self, ):
        #check if the user is an employeee
        return self.role == SystemUser.EMPLOYEE
        
class Company(models.Model):
    name = models.CharField(max_length=100)
    tagline = models.CharField(max_length=255, null=True, blank=True)
    logo = models.ImageField(upload_to='company_logos', null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    assigned_employees = models.ForeignKey(SystemUser, null=True, blank=True, related_name='assigned_companies')
    
    def __unicode__(self, ):
        return self.name
        
class Feedback(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone_number = models.CharField(max_length=20)
    comment = models.TextField()
    company = models.ForeignKey(Company, related_name='feedbacks')
    
    def __unicode__(self, ):
        return 'Feebback from ' + self.first_name + ' for ' + self.company.name

apps/feedback/forms.py
from django import forms
from feedback.models import *

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    
class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        exclude = ('assigned_employees', )
        
class EmployeeForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)
    
    
class EditEmployeeForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.EmailField()
    
class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback

apps/feedback/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic.base import View
from feedback.forms import *
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from braces.views import LoginRequiredMixin
from feedback.models import *
from django.core.exceptions import PermissionDenied
from annoying.functions import get_object_or_None
from feedback.exceptions import *
from django.contrib.auth.models import Group

class LogoutView(View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect(reverse('login-page'))

# Create your views here.
class LoginPageView(View):
    def get(self, request):
        if request.user.is_authenticated():
            #is currently  logged in user an admin?
            su = SystemUser.objects.get(user=request.user)
            if su.is_admin:
                return HttpResponseRedirect(reverse('admin-home'))
            elif su.is_employee:
                return HttpResponseRedirect(reverse('employee-home'))
            
        return render(request, 'feedback/login.html',
        {
            'form': LoginForm()
        }
        )
    
    def post(self, request):
        form = LoginForm(request.POST)
        
        if form.is_valid():
            username = request.POST.get('username')
            password = request.POST.get('password')
            
            user = authenticate(username=username, password=password)
            
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(reverse('login-page'))
                else:
                    messages.error(request, 'User is inactive')
                    return HttpResponseRedirect(reverse('login-page'))
            else:
                messages.error(request, 'Invalid username/password')
                return HttpResponseRedirect(reverse('login-page'))
        else:
            messages.error(request, 'Kindly correct the errors in the form')
            return render(request, 'feedback/login.html',
            {
                'form': form
            }
            )
            
class AdminHomeView(LoginRequiredMixin, View):
    def get(self, request):
        su = SystemUser.objects.get(user=request.user)
        if not su.is_admin:
            raise PermissionDenied
            
        return render(request, 'feedback/admin_home.html')
        
#companies       
class AdminCompaniesView(LoginRequiredMixin, View):
    def get(self, request):
        su = SystemUser.objects.get(user=request.user)
        if not su.is_admin:
            raise PermissionDenied
            
        return render(request, 'feedback/admin_companies.html',
        {
            'companies': Company.objects.all()
        }
        )
        
class CreateCompanyView(LoginRequiredMixin, View):
    def get(self, request):
        if not request.user.has_perm('feedback.add_company'):
            raise PermissionDenied
        
        return render(request, 'feedback/create_company.html',
        {
            'form': CompanyForm()
        }
        )
        
    def post(self, request):
        if not request.user.has_perm('feedback.add_company'):
            raise PermissionDenied
        
        form = CompanyForm(request.POST, request.FILES)
        
        if form.is_valid():
            form.save()
            
            messages.success(request, 'Company created successfully.')
            return HttpResponseRedirect(reverse('admin-companies'))
        else:
            messages.error(request, 'Kindly correct the errors in the form')
            return render(request, 'feedback/create_company.html',
            {
                'form': form
            }
            )
            
class EditCompanyView(LoginRequiredMixin, View):
    def get(self, request, company_id):
        if not request.user.has_perm('feedback.change_company'):
            raise PermissionDenied
        
        company = get_object_or_None(Company, pk=company_id)
        
        if not company:
            messages.error(request, 'Company not found.')
            return HttpResponseRedirect(reverse('admin-companies'))
        
        return render(request, 'feedback/edit_company.html',
        {
            'form': CompanyForm(instance=company),
            'company': company
        }
        )
    def post(self, request, company_id):
        if not request.user.has_perm('feedback.change_company'):
            raise PermissionDenied
        
        company = get_object_or_None(Company, pk=company_id)
        
        if not company:
            messages.error(request, 'Company not found.')
            return HttpResponseRedirect(reverse('admin-companies'))
            
        form = CompanyForm(request.POST, request.FILES, instance=company)
        
        if form.is_valid():
            form.save()
            
            messages.success(request, 'Changes saved successfully.')
            return HttpResponseRedirect(reverse('admin-companies'))
        else:
            messages.error(request, 'Kindly correct the errors in the form')
            return render(request, 'feedback/edit_company.html',
            {
                'form': form,
                'company': company
            }
            )
            
class DeleteCompanyView(LoginRequiredMixin, View):
    def get(self, request, company_id):
        if not request.user.has_perm('feedback.delete_company'):
            raise PermissionDenied
        
        company = get_object_or_None(Company, pk=company_id)
        
        if not company:
            messages.error(request, 'Company not found.')
            return HttpResponseRedirect(reverse('admin-companies'))
            
        company.delete()
        
        messages.success(request, 'Company deleted successfully.')
        return HttpResponseRedirect(reverse('admin-companies'))
        
#employees
class AdminEmployeesView(LoginRequiredMixin, View):
    def get(self, request):
        su = SystemUser.objects.get(user=request.user)
        if not su.is_admin:
            raise PermissionDenied
            
        return render(request, 'feedback/admin_employees.html',
        {
            'employees': SystemUser.objects.filter(role=SystemUser.EMPLOYEE)
        }
        )
        
class CreateEmployeeView(LoginRequiredMixin, View):
    def get(self, request):
        if not request.user.has_perm('feedback.add_employee'):
            raise PermissionDenied
        
        return render(request, 'feedback/create_employee.html',
        {
            'form': EmployeeForm()
        }
        )
        
    def post(self, request):
        if not request.user.has_perm('feedback.add_employee'):
            raise PermissionDenied
        
        form = EmployeeForm(request.POST)
        
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            password = form.cleaned_data['password']
            email = form.cleaned_data['email']
            username = form.cleaned_data['username']
            
            employee_group = get_object_or_None(Group, name='Employee Group')
            
            if not employee_group:
                raise MissingEmployeeGroupError('Employee Group not found')
            
            user = User.objects.create_user(username, email=email, password=password)
            
            su = SystemUser()
            su.user = user
            su.user.first_name = first_name
            su.user.last_name = last_name
            su.user.save()
            su.save()
            
            su.user.groups.add(employee_group)
            
            messages.success(request, 'Employee created successfully.')
            return HttpResponseRedirect(reverse('admin-employees'))
        else:
            messages.error(request, 'Kindly correct the errors in the form')
            return render(request, 'feedback/create_employee.html',
            {
                'form': form
            }
            )
            
class EditEmployeeView(LoginRequiredMixin, View):
    def get(self, request, employee_id):
        if not request.user.has_perm('feedback.edit_employee'):
            raise PermissionDenied
        
        su = get_object_or_None(SystemUser, pk=employee_id)
        
        if not su:
            messages.error(request, 'Employee not found.')
            return HttpResponseRedirect(reverse('admin-employees'))
            
        initial = {
            'first_name': su.user.first_name,
            'last_name': su.user.last_name,
            'username': su.user.username,
            'email': su.user.email
            }
        
        return render(request, 'feedback/edit_employee.html',
        {
            'form': EditEmployeeForm(initial=initial),
            'employee': su
        }
        )
    def post(self, request, employee_id):
        if not request.user.has_perm('feedback.edit_employee'):
            raise PermissionDenied
        
        su = get_object_or_None(SystemUser, pk=employee_id)
        
        if not su:
            messages.error(request, 'Employee not found.')
            return HttpResponseRedirect(reverse('admin-employees'))
            
        form = EditEmployeeForm(request.POST)
        
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            username = form.cleaned_data['username']
            
            su.user.username = username
            su.user.email = email
            su.user.first_name = first_name
            su.user.last_name = last_name
            
            su.user.save()
            

apps/feedback/templates/feedback/admin_companies.html
{% extends 'base.html' %}

{% block title %}Admin Companies{% endblock %}

{% block content %}

<div class="panel-group">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                    Manage Companies
            </h4>
        </div>
        <div class="panel">
            <div class="panel-body">
                <div class="row-fluid">
                    <a class="btn btn-primary push-right" href="{% url 'create-company' %}">Create Company</a>
                </div>
                {% if companies %}
                <table class="table-striped">
                    <thead>
                        <tr>
                            <th>
                                Name
                            </th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for company in companies %}
                        <tr>
                            <td>
                                {{ company.name }}
                            </td>
                            <td>
                                <a class="btn push-right" href="{% url 'feedback-company' company.id %}">View Feedback</a>
                            </td>
                            <td>
                                <a class="btn push-right" href="{% url 'edit-company' company.id %}">Edit</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}

apps/feedback/templates/feedback/admin_employees.html
{% extends 'base.html' %}

{% block title %}Admin Employees{% endblock %}

{% block content %}

<div class="panel-group">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                    Manage Employees
            </h4>
        </div>
        <div class="panel">
            <div class="panel-body">
                <div class="row-fluid">
                    <a class="btn btn-primary push-right" href="{% url 'create-employee' %}">Create Employee</a>
                </div>
                {% if employees %}
                <table class="table-striped">
                    <thead>
                        <tr>
                            <th>
                                Name
                            </th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for employee in employees %}
                        <tr>
                            <td>
                                {{ employee.user.get_full_name }}
                            </td>
                            <td>
                                <a class="btn push-right" href="{% url 'assign-companies' employee.id %}">Assign Companies</a>
                            </td>
                            <td>
                                <a class="btn push-right" href="{% url 'edit-employee' employee.id %}">Edit</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock content %} 

apps/feedback/templates/feedback/create_company.html
{% extends 'base.html' %}
{% load staticfiles widget_tweaks %}

{% block title %}
Create Company
{% endblock %}

{% block content %}

<div class="panel-group">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                    Create Company
            </h4>
        </div>
        <div class="panel">
            <div class="panel-body">
                <form class="form-horizontal" id="create-company-form" action="{% url 'create-company' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group required">
                        <label for="id_name" class="col-sm-2 control-label">Name:</label>
                        <div class="col-sm-9">
                            {{ form.name.errors }}
                            {{ form.name|attr:"class:form-control"|attr:"required"|attr:"placeholder:Name"}}
                        </div>
                    </div>
                    <div class="form-group required">
                        <label for="id_tagline" class="col-sm-2 control-label">Tagline:</label>
                        <div class="col-sm-9">
                            {{ form.tagline.errors }}
                            {{ form.tagline|attr:"class:form-control"|attr:"placeholder:Tagline"}}
                        </div>
                    </div>
                    <div class="form-group required">
                        <label for="id_logo" class="col-sm-2 control-label">Logo:</label>
                        <div class="col-sm-9">
                            {{ form.logo.errors }}
                            {{ form.logo|attr:"class:form-control"|attr:"placeholder:Logo"}}
                        </div>
                    </div>
                    <div class="form-group required">
                        <label for="id_description" class="col-sm-2 control-label">Description:</label>
                        <div class="col-sm-9">
                            {{ form.description.errors }}
                            {{ form.description|attr:"class:form-control"|attr:"placeholder:Description"}}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-primary" id="create-company-btn">Create Company</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %} 

apps/feedback/templates/feedback/create_employee.html
{% extends 'base.html' %}
{% load staticfiles widget_tweaks %}

{% block title %}
Create Employee
{% endblock %}

{% block content %}

<div class="panel-group">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                    Create Employee
            </h4>
        </div>
        <div class="panel">
            <div class="panel-body">
                <form class="form-horizontal" id="create-company-form" action="{% url 'create-employee' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group required">
                        <label for="id_first_name" class="col-sm-2 control-label">First Name:</label>
                        <div class="col-sm-9">
                            {{ form.first_name.errors }}
                            {{ form.first_name|attr:"class:form-control"|attr:"required"|attr:"placeholder:First Name"}}
                        </div>
                    </div>
                    <div class="form-group required">
                        <label for="id_last_name" class="col-sm-2 control-label">Last Name:</label>
                        <div class="col-sm-9">
                            {{ form.last_name.errors }}
                            {{ form.last_name|attr:"class:form-control"|attr:"required"|attr:"placeholder:Last Name"}}
                        </div>
                    </div>
                    <div class="form-group required">
                        <label for="id_username" class="col-sm-2 control-label">Username:</label>
                        <div class="col-sm-9">
                            {{ form.username.errors }}
                            {{ form.username|attr:"class:form-control"|attr:"required"|attr:"placeholder:Username"}}
                        </div>
                    </div>
                    <div class="form-group required">
                        <label for="id_email" class="col-sm-2 control-label">Email:</label>
                        <div class="col-sm-9">
                            {{ form.email.errors }}
                            {{ form.email|attr:"class:form-control"|attr:"required"|attr:"placeholder:Email"}}
                        </div>
                    </div>
                    <div class="form-group required">
                        <label for="id_password" class="col-sm-2 control-label">Password:</label>
                        <div class="col-sm-9">
                            {{ form.password.errors }}
                            {{ form.password|attr:"class:form-control"|attr:"required"|attr:"placeholder:Password"}}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-primary" id="create-company-btn">Create Employee</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %} 

apps/feedback/templates/feedback/edit_company.html
{% extends 'base.html' %}
{% load staticfiles widget_tweaks %}

{% block script %}
<script>
$('.delete-company').on(
            'click',
            function(evt)
            {
                evt.preventDefault();
                var $this = $(this), name = $this.data('companyname'), href=$this.data('companyurl');
                
                bootbox.confirm(
                    'Are you sure you want to delete the Company: <strong>' + name + '</strong> ?',
                    function(result)
                    {
                        if(result)
                        {
                            window.location = href;
                        }
                    }
                );
            }
        );
</script>
{% endblock %}

{% block title %}
Edit Company
{% endblock %}

{% block content %}

<div class="panel-group">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                    Edit Company
            </h4>
        </div>
        <div class="panel">
            <div class="panel-body">
                <form class="form-horizontal" id="create-company-form" action="{% url 'edit-company' company.id %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group required">
                        <label for="id_name" class="col-sm-2 control-label">Name:</label>
                        <div class="col-sm-9">
                            {{ form.name.errors }}
                            {{ form.name|attr:"class:form-control"|attr:"required"|attr:"placeholder:Name"}}
                        </div>
                    </div>
                    <div class="form-group required">
                        <label for="id_tagline" class="col-sm-2 control-label">Tagline:</label>
                        <div class="col-sm-9">
                            {{ form.tagline.errors }}
                            {{ form.tagline|attr:"class:form-control"|attr:"placeholder:Tagline"}}
                        </div>
                    </div>
                    <div class="form-group required">
                        <label for="id_logo" class="col-sm-2 control-label">Logo:</label>
                        <div class="col-sm-9">
                            {{ form.logo.errors }}
                            {{ form.logo|attr:"class:form-control"|attr:"placeholder:Logo"}}
                        </div>
                    </div>
                    <div class="form-group required">
                        <label for="id_description" class="col-sm-2 control-label">Description:</label>
                        <div class="col-sm-9">
                            {{ form.description.errors }}
                            {{ form.description|attr:"class:form-control"|attr:"placeholder:Description" }}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-primary" id="create-company-btn">Save Changes</button>
                        <button data-companyname="{{ company.name }}"  data-companyurl="{% url 'delete-company' company.id %}" type="submit" class="btn btn-danger delete-company" id="del-company-btn">Delete Company</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %} 
 

apps/feedback/templates/feedback/edit_employee.html
{% extends 'base.html' %}
{% load staticfiles widget_tweaks %}

{% block script %}
<script>
$('.delete-employee').on(
            'click',
            function(evt)
            {
                evt.preventDefault();
                var $this = $(this), name = $this.data('employeename'), href=$this.data('employeeurl');
                
                bootbox.confirm(
                    'Are you sure you want to delete the Employee: <strong>' + name + '</strong> ?',
                    function(result)
                    {
                        if(result)
                        {
                            window.location = href;
                        }
                    }
                );
            }
        );
</script>
{% endblock %}

{% block title %}
Edit Employee
{% endblock %}

{% block content %}

<div class="panel-group">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                    Edit Employee
            </h4>
        </div>
        <div class="panel">
            <div class="panel-body">
                <form class="form-horizontal" id="edit-employee-form" action="{% url 'edit-employee' employee.id %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group required">
                        <label for="id_first_name" class="col-sm-2 control-label">First Name:</label>
                        <div class="col-sm-9">
                            {{ form.first_name.errors }}
                            {{ form.first_name|attr:"class:form-control"|attr:"required"|attr:"placeholder:First Name"}}
                        </div>
                    </div>
                    <div class="form-group required">
                        <label for="id_last_name" class="col-sm-2 control-label">Last Name:</label>
                        <div class="col-sm-9">
                            {{ form.last_name.errors }}
                            {{ form.last_name|attr:"class:form-control"|attr:"required"|attr:"placeholder:Last Name"}}
                        </div>
                    </div>
                    <div class="form-group required">
                        <label for="id_username" class="col-sm-2 control-label">Username:</label>
                        <div class="col-sm-9">
                            {{ form.username.errors }}
                            {{ form.username|attr:"class:form-control"|attr:"required"|attr:"placeholder:Username"}}
                        </div>
                    </div>
                    <div class="form-group required">
                        <label for="id_email" class="col-sm-2 control-label">Email:</label>
                        <div class="col-sm-9">
                            {{ form.email.errors }}
                            {{ form.email|attr:"class:form-control"|attr:"required"|attr:"placeholder:Email"}}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-primary" id="create-employee-btn">Save Changes</button>
                        <button data-employeename="{{ employee.user.first_name }}"  data-employeeurl="{% url 'delete-employee' employee.id %}" type="submit" class="btn btn-danger delete-employee" id="del-employee-btn">Delete Employee</button>
                        </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}  